### PR TITLE
CRLF formatting fix

### PR DESCRIPTION
**Pull request by mseddon**
Associated fixes: https://github.com/BetterThanTomorrow/calva-fmt/pull/9

### CODE REVIEW

**Comment by mseddon** [comment]
Okay, fixed the tests. Basically I needed to remember to pass `:eol "\n"` into the appropriate calls.

**Comment by mseddon** [comment]
Removed the `shadow-cljs :exports` that I migrated from the old branch.
All tests pass except the 6 known failures, LGTM, but see what you think.

**Comment by PEZ** [comment]
The `:release` build doesn't work. The functions used by `calva-fmt` need to be exported.

**Comment by mseddon** [comment]
Closing this for now since you have released a decent fix. 😀

**Pull request closed without merging**
